server:
  port: 8085
leanix:
  vsm:
    base-url: http://localhost:8080
    event-broker:
      base-url: http://localhost:8083
    dora:
      base-url: http://localhost:8084
    auth:
      access-token-uri: https://test-app-1.leanix.net/services/mtm/v1