
leanix:
  base-url: https://${LEANIX_DOMAIN}/services
  vsm:
    base-url:  ${leanix.base-url}/vsm-canopy/v1
    event-broker:
      base-url: ${leanix.vsm.base-url}/vsm-events-broker
    dora:
      total-days: 30
      base-url: ${leanix.base-url}/vsm-dora-events/v1/dora
    connector:
      api-token: ${LEANIX_API_TOKEN}
      user-token: ${LEANIX_USER_TOKEN}
      config-name: ${LEANIX_CONFIGURATION_NAME}
      github-token: ${GITHUB_TOKEN}
      github-url: ${GITHUB_URL}
      github-version: ${GITHUB_VERSION:v3}
      broker-url: ${BROKER_URL:""}
    auth:
      access-token-uri: ${leanix.base-url}/mtm/v1
    webhook:
      enabled: ${VSM_WEBHOOK:true}
