server:
  port: 8085
leanix:
  vsm:
    base-url: http://localhost:8080
    event-broker:
      base-url: ${leanix.vsm.base-url}
    connector:
      api-token: ${LEANIX_API_TOKEN}
      user-token: ${LEANIX_USER_TOKEN}
      config-name: ${CONFIGURATION_NAME}
    auth:
      access-token-uri: https://test-svc-1.leanix.net/services/mtm/v1