
leanix:
  vsm:
    base-url:  https://${LEANIX_REGION}.leanix.net/
    event-broker:
      base-url: https://${LEANIX_REGION}.leanix.net/
    connector:
      api-token: ${LEANIX_API_TOKEN}
      user-token: ${LEANIX_USER_TOKEN}
      config-name: ${CONFIGURATION_NAME}
      github-token: ${GITHUB_TOKEN}
      github-url: ${GITHUB_URL}
    auth:
      access-token-uri: https://${LEANIX_REGION}.leanix.net/services/mtm/v1